### ISSUE TITLE
using the self-loop filter changes the size of edges rather than filtering nodes

### ISSUE THREAD

**Issue by ludist** [gephi/gephi#1040]
![image](https://cloud.githubusercontent.com/assets/5781922/7036385/e6daba70-dd59-11e4-8b13-9fc3e3f92d8f.png)

**Comment by mbastian** [comment]
Hi, there is an explanation for that. The self-loop filter isn't intended to filter the nodes but the edges. The filter would remove all self-loop edges from the graph. Because we rescale edge weights for visualization purposes removing edges may indeed change the edge thickness in 0.8.2. This issue (#538) has been fixed and will be included in the upcoming 0.9 release. Also, we created a "Has self-loop" node filter to address your use-case, which is legitimate. That will also be included in the upcoming release and is tracked at #1203.
