### ISSUE TITLE
 Forced Termination

### ISSUE THREAD

**Issue by lyrewu** [gephi/gephi#1046]
After setup, it is forced termination when open it. Try it many times in many computers.

**Comment by eduramiba** [comment]
Probable duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.
