### ISSUE TITLE
Diameter calculation

### ISSUE THREAD

**Issue by davanT420** [gephi/gephi#1089]
I'm wondering about the graph diameter calculation at modules/StatisticsPlugin/src/main/java/org/gephi/statistics/plugin/GraphDistance.java 

Graph diameter is commonly defined in the sense of the maximum eccentricity of any node in the network [graph]. Wikipedia states this as "The eccentricity \epsilon(v) of a vertex v is the greatest geodesic distance between v and any other vertex. It can be thought of as how far a node is from the node most distant from it in the graph." You'll find similar definitions in the networkx and IGraph/R packages.

Yet the calculation here is programmed as [line 231-233]:

nodeEccentricity[s_index] = (int) Math.max(nodeEccentricity[s_index], d[i]);
nodeCloseness[s_index] += d[i];
diameter = Math.max(diameter, d[i]);

What exactly is the benefit here of using d[i], instead of simply stating:

diameter = Math.max(diameter, nodeEccentricity[s_index])

especially given the fact that only a few lines above the program takes account that d[r_index] can turn negative [which is impossible for eccentricity]?

**Comment by jacomyma** [comment]
Your solution and the original code to the same thing, the diameter calculations is the right one. Here is some explanation.

The diameter is the maximum distance in the graph. There is at least one pair of nodes whose distance is the diameter.
The Eccentricity of a node is its maximum distance with other nodes. At least two nodes have a distance equal to the diameter, so both nodes will have an eccentricity equal to the diameter.

Original code takes the max distance among pairs of nodes. Your code takes the max among eccentricities. Both strategies will reach the maximum distance possible, thus computing the right diameter.

I do not think your solution is significantly better than the other. It is probably more efficient but this computing is only made once so it does not matter much. On the other hand the original work is more straightforward, since you can understand the diameter without knowing what is eccentricity.
