### ISSUE TITLE
[0.9 nightly] Java 7 not found

### ISSUE THREAD

**Issue by Yomguithereal** [gephi/gephi#1219]
When starting `gephi` bin on Ubuntu 12, the program tells me "Java 7 standard edition or newer required" while I do have a Java 7 installed (openjdk) and a valid JAVA_HOME.

However, the error can be circumvented by launching gephi likewise:

```
./gephi --jdkhome $JAVA_HOME
```

**Comment by RouxRC** [comment]
same here:
```bash
$ java -version
java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-0ubuntu0.12.04.1)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)
$ bin/gephi
Error window saying to give proper jdkhome path
$ bin/gephi --jdkhome /usr/lib/jvm/java-7-openjdk-amd64/
Good
```

**Comment by mbastian** [comment]
Thanks for the report, this is due to the way the netbeans launcher is designed, which is something we don't tweak at this point. I don't actually understand why the launcher doesn't try to look for JAVA_HOME, seems pretty straightforward. Some details here https://netbeans.org/bugzilla/show_bug.cgi?id=198950

**Comment by wetneb** [comment]
This can be closed now that the JRE is embedded in the forthcoming releases on all platforms.
