### ISSUE TITLE
GDF import no longer allows to set directedness

### ISSUE THREAD

**Issue by bernorieder** [gephi/gephi#1246]
In previous versions GDF files without the "directed" edge attribute could be opened as directed, this is no longer possible. Tools can be adapted to add the edge attribute (which works fine), but old files pose problem.

**Comment by mbastian** [comment]
You are correct, this was changed to follow the specification (see #906) but I understand the transition problem. There's no way to set a global parameter in GDF. I don't have a solution to propose at this point because if the graph is imported as undirected it can't be forced to be directed as we check for edge duplicates and so on.

**Comment by eduramiba** [comment]
Proposed transition solution: import with 0.8.2 and export a gexf file. Then import it with 0.9

**Comment by bernorieder** [comment]
OK, I've added the "directed" attribute to all our tools where we use GDF and the transition solution should be workable for old files. Thanks a lot for all the hard work!
