### ISSUE TITLE
Issues with Mac OS 10.10.5

### ISSUE THREAD

**Issue by shainarace** [gephi/gephi#1277]
I have legacy Java installed.

Still having several issues clicking around the interface - locking up, strange behavior (calculated variables like page rank are populating the pull-down menu for node color but not node size, then suddenly appear in node size 10 minutes later). After importing spreadsheet data, clicking back and forth between data laboratory and overview locks up every time.

**Comment by akras14** [comment]
+1 would love to provide more info on my set up if needed.

**Comment by rotten** [comment]
I'm running 10.11.2.  My macbook has 4 cores and 16g ram.  (an i7 macbook pro)
I'm using Oracle Java version "1.8.0_66"

I bumped up -Xmx to 10G.

I was not able to get Gephi 9.0 to run.  It would start, but just hang, with no warnings on the command line or on the screen.   I was able to get 9.1, pulled from this repo last week, to run.

I loaded up a graph with 50,000 or so nodes.   It was slow, but it seemed to work - mostly ... I am seeing strange things as well,  sometimes it just becomes unresponsive, sometimes the screen paints (after a resize or move) don't work until I tab to Data Laboratory and then back to Overview.  At first the toolbar across the bottom of the graph in Overview was not there.  I was fiddling around with my graph and then suddenly the toolbar appeared and has been there since.

-> Filters do not work.  They just blank the screen and then hang forever. 

The clustering plugins seem to have disappeared, as have things like the circle layout.

I'll try going back to version 8 in another folder and see if I have issues there too, or if they are unique to 9.x.

I don't have a windows machine handy to try Gephi on for comparison.

**Comment by mbastian** [comment]
Please try again with 0.9.1 as it addressed a couple of issues you mentioned

**Comment by rotten** [comment]
Thanks!  I tried it again as soon as 0.9.1 came out and it works much better now!  I haven't observed any serious issues yet.  Thanks for the fixes!!!!  :-)  Gephi is much better than Cytoscape for my purposes, which is was I was using during these dark times between working versions...

**Comment by akras14** [comment]
I can confirm too, that it works fine for me with the latest version.
