### ISSUE TITLE
Migrate spreadsheet importer to Import API

### ISSUE THREAD

**Issue by eduramiba** [gephi/gephi#1282]
Move the import merging logic out of data laboratory by using importer + processor.
This would also make it possible to use the import report panel to list problems, etc.

Work in progress at: https://github.com/eduramiba/gephi/tree/spreadsheet-migrate

**Comment by eduramiba** [comment]
Unit tests should be added before migration and checked after migration.

**Comment by WouterSpekkink** [comment]
So, as discussed on Facebook, it would be nice if the import API would also handle time-stamped data automatically. I attached an example edge list. The data are made up.

The most important characteristic of the list in this context is that certain edges occur more than once, but at different times. This is typical, for example, for data that is based on communications (e.g., emails). In the example, see the edges from Fred to Alice and from Dirk to Fred. Both occur twice, but at different times.

The issue is that, when imported as an edge list in Gephi, both these edges will be imported only once. They are not automatically recognized as intervals, because an interval variable is not included in the edge list yet. However, it would be nice for Gephi to recognize the time stamp, and parse duplicate edges into intervals automatically. 

Perhaps I am overlooking something, but I believe this is not possible yet. I am also not that sure how reasonable it is to expect Gephi to recognize and parse time stamps appropriately, as different formats for timestamps could be used. However, given that many datasets are likely to be structured in this way, it would be a useful feature. Currently, I have to work with workarounds implemented in Excel/Libreoffice itself.

**Comment by eduramiba** [comment]
@WouterSpekkink Thanks Wouter, I will take this into account. I think I actually have already, you can try it building this branch: https://github.com/eduramiba/gephi/tree/spreadsheet-migrate

Look at these screenshots for a demo of the new process (I changed date formats to ISO 8601) so they are automatically detected and parsed as TimestampSet (the second wizard step now auto-detects column types in most cases :D):

![1](https://cloud.githubusercontent.com/assets/197285/23093130/b049aaca-f5da-11e6-9fd7-2430d4747344.png)
![2](https://cloud.githubusercontent.com/assets/197285/23093129/b0485062-f5da-11e6-8408-dc43c25dae03.png)
![3](https://cloud.githubusercontent.com/assets/197285/23093131/b04cf7a2-f5da-11e6-8ab1-2aa63d1535b9.png)
![4](https://cloud.githubusercontent.com/assets/197285/23093128/b0485526-f5da-11e6-81c9-4553cfbe00d6.png)

**Comment by WouterSpekkink** [comment]
Awesome. That is exactly what I meant. Great that this has already been
worked on. Thanks a bunch!

2017-02-18 12:05 GMT+00:00 Eduardo Ramos <notifications@github.com>:

**Comment by Marmeladenbrot** [comment]
Is it possible to do the same for duplicate Nodes with timestamps?

Right now duplicated Nodes get deleted and a single Node remains but all timestamps from the other Nodes are lost and there is no way to prevent this in Gephi.

**Comment by eduramiba** [comment]
@Marmeladenbrot See https://github.com/gephi/gephi/issues/1984#issuecomment-401284812
