### ISSUE TITLE
Appearance Window hangs after setting size

### ISSUE THREAD

**Issue by JVot** [gephi/gephi#1324]
Whenever I press the "Apply" button to set the Node Size to an integer value, (min 10 / max 100), the Apply works within the Graph, but then the Appearance window hangs.  

I can press the buttons for Nodes/Edges and for Color/Size/Label Color/Label size and for Unique/Attribute, but nothing changes within the window.  Its frozen with the Attribute drop down and min/max size that was chosen when I did the first Apply.

Gephi 0.9.0 and ran check for updates
Java version jre1.8.0_71

**Comment by mbastian** [comment]
Interesting, I can't reproduce this. Does it happen with a certain graph only? Can you try with the sample graph as well?

**Comment by JVot** [comment]
Good question.  It does seem to be data specific as the Les Miserable sample file does not seem to have the issue.  I'll try to upload the scrubbed data files.

**Comment by JVot** [comment]
[Sample Nodes.xlsx](https://github.com/gephi/gephi/files/110096/Sample.Nodes.xlsx)
[Sample Edges.xlsx](https://github.com/gephi/gephi/files/110097/Sample.Edges.xlsx)

**Comment by mbastian** [comment]
Good, thanks for the files I can now reproduce the issue.

**Comment by mbastian** [comment]
Hi, the bug appears because you have a `NULL` value in your column. This is due to the fact your "Sample Edges" file has a `NULL` destination node, which end up being created in your graph. I've made some improvements to the error logging so now you would get a message that a value is null. If that happens it also won't hang anymore.
