### ISSUE TITLE
Failed to write core dump. Core dumps have been disabled. (Gephi 0.9.1)

### ISSUE THREAD

**Issue by shakedzy** [gephi/gephi#1442]
Hi,
Just downloaded Gephi 0.9.1 on Ubuntu 15.10 64bit with Oracle Java 8.
Trying to run Gephi, I get this error every time I try to load a project:

```
 A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fddbf65173c, pid=13738, tid=140590311270144
#
# JRE version: Java(TM) SE Runtime Environment (8.0_77-b03) (build 1.8.0_77-b03)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.77-b03 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [i965_dri.so+0x20273c]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
```

Log file is attached.
[hs_err_pid11765.log.zip](https://github.com/gephi/gephi/files/195363/hs_err_pid11765.log.zip)

Any ideas what's going on?

**Comment by eduramiba** [comment]
This kind of error is often related to outdated graphic drivers. Can you try to update them?

**Comment by shakedzy** [comment]
This computer is 2 months old..
I use the default graphic driver that came with Ubuntu 15.10. What now?
I'm using a Lenovo X1 Carbon if it helps..

**Comment by eduramiba** [comment]
This really depends on your model and OS. With Linux is specially tricky too.

Did it come with Linux? I can't find official drivers here http://support.lenovo.com/us/en/products/laptops-and-netbooks/thinkpad-x-series-laptops/thinkpad-x1-carbon-type-20a7-20a8?beta=false

You can try this http://askubuntu.com/questions/619848/video-drivers-installed-but-no-webgl-or-opengl-acceleration-working or similar...

**Comment by shakedzy** [comment]
No. Doesn't work either..

**Comment by computermacgyver** [comment]
The [Lenovo page](http://www3.lenovo.com/au/en/laptops/thinkpad/thinkpad-x/X1-Carbon-3rd-Generation/p/22TP2TXX133#tab-tech_specs) shows it has an Intel HD Graphics 5500. This is usually well supported out-of-the-box on Linux, but you could nonetheless try the [Intel Graphics Installer](https://01.org/linuxgraphics/downloads/intel-graphics-installer-linux-1.4.0) . And do double check with ``lspci`` and ``lshw -c video`` that the expected drivers are installed.

It is probably worth also following the prompt and running ``ulimit -c unlimited`` in a terminal before launching Gephi in that same terminal window in order to be able to generate a core dump and get more details on the error.

**Comment by shakedzy** [comment]
Didn't work either..

**Comment by crsqq** [comment]
Same problem here but with ubuntu 16.04 and a lenovo t450s.

Found a workaround in [issue 1192](https://github.com/gephi/gephi/issues/1192#issuecomment-179088499):

```
LIBGL_ALWAYS_SOFTWARE=1 ./gephi
```

Haven't noticed any performance issues yet but I think that this may be the case if you work with larger graphs.

**Comment by rajasekharreddykrify** [comment]
[java_error_in_STUDIO_2407.log.zip](https://github.com/gephi/gephi/files/376536/java_error_in_STUDIO_2407.log.zip)
