### ISSUE TITLE
Gephi 0.9.1 Uninstall

### ISSUE THREAD

**Issue by fmahieux** [gephi/gephi#1446]
Cannot restore a gephi 0.8.2 once Gephi 0.9.1 has been installed once.

**Comment by eduramiba** [comment]
What error do you get?

**Comment by fmahieux** [comment]
Hi, i've got no error. Gephi 0.8.2 starts with splashscreen then stops.
Thanks for your help.
Francis Mahieux

Le 1 avr. 2016 2:30 PM, Eduardo Ramos <notifications@github.com> a écrit :What error do you get?

**Comment by eduramiba** [comment]
That sounds like the fixed major issue with java #748 

Gephi 0.8.2 does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

For Mac OS please try this http://sumnous.github.io/blog/2014/07/24/gephi-on-mac

For Windows check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712

**Comment by fmahieux** [comment]
Hi,
Indeed, re-installing jdk 7 resolved my case.
Thanks for your help.Regards
Francis Mahieux



Date: Fri, 1 Apr 2016 16:07:38 -0700
