### ISSUE TITLE
Incorrect average degree for directed graphs

### ISSUE THREAD

**Issue by ooof** [gephi/gephi#1455]
It should be 0.5 ?

![default](https://cloud.githubusercontent.com/assets/392785/14403487/5345662c-fe8a-11e5-9885-989ce5b31e66.PNG)

**Comment by duncdrum** [comment]
Average degree is ````2x the number of edges / number of nodes````. See [here](http://barabasi.com/f/625.pdf) p. 8 (2.2). So ````1```` is the correct result.

**Comment by eduramiba** [comment]
Thanks, closing this as it's not an issue.

**Comment by duncdrum** [comment]
actually the op is correct, i didn't notice that we have a directed network.  The correct formula for directed would indeed be ````number of edges / number of nodes'```` so ````0.5````` would be the correct result. See [here](http://barabasi.com/f/625.pdf) p. 9 (2.5). @eduramiba Please re-open this is a bug. The function uses the undirected formula for a directed network.

**Comment by eduramiba** [comment]
Oh ok, will have to review this then.

**Comment by ooof** [comment]
Thank you!
I will learn.
If you need to remove it.

**Comment by mbastian** [comment]
Thank you for the pointers, I finally fixed that. Weighted degree should also be consistent with it now.

**Comment by VictorSeven** [comment]
I see this is closed, but I still can see the issue in Gephi 0.9.2 201709241107. Is it really fixed?

**Comment by VictorSeven** [comment]
In fact, I think the OP is mistaken here. Think about this: in the OP example, if the network is indirected, the average degree is 1. In a directed network, there are three different quantities: in-degree, out-degree and total degree. Average in- and out-degree is 0.5. However, mean degree is still 1.0 -because it has to count both edges going in and out. 

I will show it clearly using Gephi with a more serious example. Let's say we want to generate an Erdos-Renyi directed random graph with fixed average degree, say <k>=6. 

Then, go to File > Generate > Random Graph. We are asked the probability of connection. We know that this is related to the average degree <k> as: p = <k>(N-1), where N is the number of nodes. We create a network with N=1000 and <k>=6, so p=0.006. 

Now we ask Gephi the average degree of the network. This is the result:
![captura de pantalla de 2018-01-11 18-20-48](https://user-images.githubusercontent.com/16043960/34837824-4ca145c2-f6fc-11e7-8bdd-c5ae6b3c86f6.png)

As you can see, the degree distribution has a peak on 6.0, just as we wanted. But the average degree displayed is 3.0, which is the half -and it is incorrect.

**Comment by gmoutsin** [comment]
> In fact, I think the OP is mistaken here. Think about this: in the OP example, if the network is indirected, the average degree is 1. In a directed network, there are three different quantities: in-degree, out-degree and total degree. Average in- and out-degree is 0.5. However, mean degree is still 1.0 -because it has to count both edges going in and out.

Think of the undirected graph {1-2} and the directed graph {1->2,2->1}. They are essentially the same graph, but according to your logic the first one has average degree 1 and the second average degree 2.
