### ISSUE TITLE
Filter is changed after saving file and opening again

### ISSUE THREAD

**Issue by FlxVctr** [gephi/gephi#1511]
I filter a directed network on Attribute>inter edges>modularity class. After saving and reopening, the filter is changed to inter edges>another attribute (in my case a user name). (Gephi 0.9.1 on Mac OS X 10.11.4)

**Comment by ytoto** [comment]
Similar problem here on Attributes > Equal:
- save, quit and open project, filter name changed with wrong attribute name
- sometimes attribute name changed also
- duplicate filter contextual menu produces a filter with another attribute name
- Operator > UNION, can't rename that filter

Last one is a feature request maybe ...
As I'm a noob Gephi user, can you give me some hint to workaround those little problems !

A part that, thank you for this really neat tool !
I use it since a couple of days and already can't live without ;)
Keep up the good work :heart:

--8<--- version info
Gephi 0.9.1 official
debian jessie openjdk-7-jre 7u121-2.6.8-2~deb8u1
