### ISSUE TITLE
Wrong quantity of connected component

### ISSUE THREAD

**Issue by hmcristovao** [gephi/gephi#1545]
Dear.

[network with 2 connected components - error.zip](https://github.com/gephi/gephi/files/384490/network.with.2.connected.components.-.error.zip)

The attached graph has 2 connected components, but Gephi only show 1 connected component in statisctic window and also in the use of your library, Gephi Toolkit.  

This network is small, with 24 nodes conected itself and it has 1 node alone. Hence it should have 2 component connected.

Thanks.

**Comment by eduramiba** [comment]
It seems a single node is not being counted as a component. I think that is indeed wrong.

**Comment by duncdrum** [comment]
I have a hard time locating mentions of individual nodes as components. Intuitively it doesn't make much sense to me to treat individual nodes as components. E.g. Barabási, Albert-László. Network Science, 2016. http://barabasilab.neu.edu/networksciencebook/. p 24-5. starts from the assumption that _pairs_ of nodes can form components which are either connected or not. Can anybody point to a source where individual nodes are treated as components?

The problem is more complex since the sample file contains self-connected node (node-ID 5785 U.S.), but the single-node-component in question isn't one of them. A self-connected node would make more sense as a component, since it has a path from which it can reach something. 

Given the sample graph, I would indeed expect there to be only _one_ connected component. However, the isolated node should not be part of that component, but for some reason gephi thinks it is (color nodes by component ID shows this). 
![screenshot 2016-08-22 12 13 49](https://cloud.githubusercontent.com/assets/6205362/17851692/ac7ab402-6863-11e6-8c33-da2aa3f4b75c.png)

I don't get the option of using a directed component detection algorithm although this is a directed network. So something else is going wrong here as well.

**Comment by kgreenfield** [comment]
A connected component in an undirected graph is defined as a maximal set of nodes such that there exists a path between every pair of nodes in the set.  In a directed graph, a directed connected component is defined as a maximal set of nodes such that there is a path from every nodes in the set to every other node in the set.  In both cases, a single node with degree 0 is a connected component. 

This issue is broader than that though.  I'm also getting cases where a pair of nodes connected by an edge is being lumped in with another connected component.  In my cases, it looks like it is always one or more small connected components being lumped in with the giant component (which was given component id 0).

**Comment by mbastian** [comment]
Thanks for the details, but still unclear whether we should change something here?

**Comment by kgreenfield** [comment]
Yes, there is a bug here and the code should be changed. Isolated nodes are consistently not being counted as connected components (they should be) and are being assigned component is 0, which incorrectly affects filtering by component id. This incorrect behavior is also sometimes seen with diads (2 nodes which are connected to each other by a single edge and not connected to anything else).

**Comment by duncdrum** [comment]
Agreed, the graph I posted is coloured by component-id the isotope should not be the same color as the strongly connected component. @kgreenfield could you point me to a source that elaborates on why zero-degree nodes are treated as components.

**Comment by kgreenfield** [comment]
I'm unfortunately not currently in the office where I keep my graph theory books, but here is a snippet I found that clearly states that 0-degree nodes are treated as connected component - https://books.google.com/books?id=i-bUBQAAQBAJ&pg=PA619&dq=connected+component&hl=en&sa=X&ved=0ahUKEwih45_Vm_PPAhUDcj4KHdVXDC0Q6AEIHjAA#v=onepage&q&f=false.  Also, if you follow the algorithm in your citation, you will see that it also treats 0-degree nodes as connected components.  As for why this is the case (as derived from the definition that a pair of nodes are in the same connected component if and only if there is a path connecting them), consider a single 0-degree node called A.  A is connected to itself via the trivial path (path with no edges).  As for why this was chosen to be the definition, it's because it was a convenient definition to build off of.  This way you can do things like say that a graph is equal to the union of all of it's connected components.

**Comment by eduramiba** [comment]
I think according to box 2.6 at http://barabasi.com/networksciencebook/chapter/2#connectedness a single node would be a component.

**Comment by duncdrum** [comment]
@eduramiba & @kgreenfield thanks for the links, I see now that this is indeed the case. 

So in the sample in question we should have **two** connected components, and **one** strongly connected component. If the isolated node had a self-loop, we would have **two** strongly connected components? Sounds like something for the test suite?

**Comment by kgreenfield** [comment]
@duncdrum Not quite.

A single node with degree 0 is both a weakly connected component and a strongly connected component.

The example graph has 2 weakly connected components: component 1 consists of the single 0-degree node and component 2 consists of everything else.

This graph has many strongly connected components.  I just eye-balled it, but I believe that every node in this graph is it's own strongly connected component.  In order for 2 nodes to be in the same strongly connected component, there must be a path from the first node to the second node and also a path from the second node to the first node.

A note on vocabulary - when people use the phrase "connected component" when talking about directed graphs, they typically mean weakly connected component.
