### ISSUE TITLE
gephi does not start: No way to find original stream handler for jar protocol

### ISSUE THREAD

**Issue by julenl** [gephi/gephi#1651]
## Expected Behavior
Some graphic interface should open and respond to clicks.

## Current Behavior
It crashes from the command line on the first run with java 9. With java 7 (Middle security) and 8 starts the GUI, but it is either not responding to clicks or loading a file does not work. The viewer is scrambled or blank.

## Steps to Reproduce
1. wget https://github.com/gephi/gephi/releases/download/v0.9.1/gephi-0.9.1-linux.tar.gz
2. PATH/TO/GEPHI_DIR/bin/gephi --jdkhome $JAVA_HOME
3. If the GUI loads, try unsuccesfully to load some gefx file

## Context
I was just trying to give gephi a try.

## Your Environment

* Version used: Gephi 0.9.1
* Operating System: Lubuntu 16.04.1 LTS, Kernel 4.4.0-57-generic, openjdk-7/8/9-jre and oracle ones

[hs_err_pid3049.txt](https://github.com/gephi/gephi/files/696142/hs_err_pid3049.txt)

**Comment by eduramiba** [comment]
It's a crash due to broken graphic card drivers in linux. It's actually very common, it happens in my ubuntu too.

There is two ways to fix it that worked for me:

* Forcing software rendering, see https://github.com/gephi/gephi/issues/1064#issuecomment-221266392
* Using latest Mesa drivers (11.3-dev, which are beta). See https://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-16.04-OI-Intel-GL-4.2

**Comment by julenl** [comment]
Thank you very much @edumiba! I just tried forcing the software rendering and everything worked perfectly :)
Maybe it would be an option to make it a default, at least for linux systems...
