### ISSUE TITLE
Node size/colour stops changing in dynamic network

### ISSUE THREAD

**Issue by hochfilzer** [gephi/gephi#1782]
## Expected Behavior
The size and the colour of the nodes in a dynamic network according to some attribute should change according to node attributes.

## Current Behavior
I am working with a network having 40 nodes and 1700 timesteps. The node size and colour stop changing according to the changing node attributes after around 600 timesteps and the nodes remain to have the same colours and sizes as at the ~600th timestep. I have to press Stop and Start again at the Appearance window for it to work again for a few hundred timesteps.
I have activated the AutoApply button.

## Steps to Reproduce

1.
2.
3.
4.

## Context
I am trying to film the dynamic network on my screen.

## Your Environment

* Version used: Gephi 0.9.2 snapshot
* Operating System: MacOS El Capitan

**Comment by eduramiba** [comment]
Can you provide a sample file and the exact steps you follow?

**Comment by Leowler** [comment]
Thanks for the quick reply!

I cannot provide the data I am using I'm afraid since it's sensitive. However I created a random network with just two nodes and 2000 time steps, and after about 1000 steps the size of the nodes stopped changing (the colour continued to change). At a different trial the opposite happened, the colour stopped changing while the size continued to change.

My steps:

- I set the node size to be according to DynAttr between 10 and 50
- I set the node colour to be according to DynAttr2, using a custom colour scale from red to green
- I enable the timeline, set the custom bound from 1 to 2 and set the step size to 0.05%

I noticed that in the Appearance window I the node colour settings open when the size stopped changing, and I had the node size settings open when the colour stopped changing - perhaps there is a relation.

I have tried it with the original network very often. Unfortunately both, the colour and the size stop changing after a certain time every time I tried.

The file:
[simple_example.gephi.zip](https://github.com/gephi/gephi/files/1303301/simple_example.gephi.zip)

**Comment by eduramiba** [comment]
I can't reproduce this with 0.9.2 SNAPSHOT on Windows. What version of Java are you using? Can you make a video?

**Comment by eternalmr** [comment]
Hi @eduramiba, I'm trying to produce a dynamic network which node color and size changing over time, would you teach me how to implement this, thanks

**Comment by mbastian** [comment]
Hi, thanks for the report. I suggest to try again with the latest Gephi version as since 0.9.3 there has been a lot of fixes on the Appearance module. Feel free to reopen if it persists.
