### ISSUE TITLE
Multiple pdf/svg/png/gefx export with settings

### ISSUE THREAD

**Issue by mihkal** [gephi/gephi#1791]
## Expected Behavior
One could export all the workspaces at once with same resolution. 
export to folder name = project name
file names = workspace names
include possibilty for exporting settings for
- layout used
- filter used
- coloring/size/etc used per file

## Current Behavior
Single file export

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by mbastian** [comment]
We've implemented this feature and it will be in the next 0.10.0 release.

There is a new option "Export all workspaces" on the export dialog. When selected - in combination with a selected folder - will export all workspaces, instead of just the one currently selected.
<img width="633" alt="Screenshot 2022-11-09 at 20 11 28" src="https://user-images.githubusercontent.com/234813/200920555-29540008-dc21-47b8-b963-606b291143e9.png">

It will use the workspace name as filename.
