### ISSUE TITLE
Import CSV error edges

### ISSUE THREAD

**Issue by jorgaf** [gephi/gephi#1848]
## Expected Behavior
Import a CSV file and get 176 nodes and 246 edges.

## Current Behavior
I get 176 nodes, but only 225 edges.

## Possible Solution
Review import spread sheets.

## Steps to Reproduce

1. In Gephi 0.9.1 and 0.9.2 import attachment CSV file like as edge table
2.  In version 0.91 you will get 176 nodes and **246 edge**, but in 0.9.2 you will get 176 and **225 edges**.

## Your Environment

* Version used: Gephi 0.9.2 201709242018
* Java version: 1.8.0_144; Java HotSpot(TM) 64-Bit Server VM 25.144-b01
* Operating System: Mac OS X versión 10.13.1 que se ejecuta en x86_64; UTF-8; es_ES (gephi)

**Comment by eduramiba** [comment]
Can you attach the file? What edge merge strategy do you choose during import report? Do you get any warning in the report?

**Comment by jorgaf** [comment]
[The file](http://j4loxa.com/sna/gephi/graph_hashtags.csv). The strategy was sum and I did not get any warning, the message was about merge strategy.
I am doing some test. I am not sure, but the problem is when the file is something like this:
Source,Target
loja,postalecu911
postalecu911,loja

The report show me nodes: 2 and edges: 2. If I select undirected graph, it has not edge, but if I choose directed graph, it has one edge between nodes.

**Comment by eduramiba** [comment]
Ok, If I choose directed and sum, I get the 246 edges.

The problem is, when undirected, opposite edges cannot coexist, and they should be merged, but it seems no edge is created at all when opposite undirected edges exist.

I will investigate this problem, thanks for the report!

**Comment by eduramiba** [comment]
After fixing this problem, now forcing undirected correctly includes an `loja,postalecu911` edge with Weight = 2, but the final amount of edges is 224 (might be right, due to opposite undirected edges being incompatible).
It seems everything is fine, so I am not sure if I am missing something... Can you please check the new output and confirm it's fine? This is what it produces: 
[testEdgesTableOppositeForceUndirected_Issue1848_edges.zip](https://github.com/gephi/gephi/files/1484154/testEdgesTableOppositeForceUndirected_Issue1848_edges.zip)

**Comment by jorgaf** [comment]
I checked the new graph. It looks ok.
I am closing the issue.

**Comment by eduramiba** [comment]
Great, thanks! I will merge this soon into master, so next 0.9.3-SNAPSHOT should contain the fix.
Also, this fix will be available in next batch of updates for 0.9.2 (in-app Tools-Plugins menu) soon.
