### ISSUE TITLE
java  use JNA call a C method, encounter following problem,who can help me?

### ISSUE THREAD

**Issue by lovingcodesk** [gephi/gephi#1967]
*** Aborted at 1526195283 (unix time) try "date -d @1526195283" if you are using GNU date ***
PC: @     0x7fd54141fc3a (unknown)
*** SIGSEGV (@0x1c) received by PID 32589 (TID 0x7fd559cf2700) from PID 28; stack trace: ***
    @     0x7fd55953f4b0 (unknown)
    @     0x7fd54141fc3a (unknown)

**Comment by eduramiba** [comment]
Can you add some info about your environment?

Anyway try to use latest java 8 version and make sure your graphics card drivers are up to date,  these cause most of the problems in Linux.

**Comment by eduramiba** [comment]
Try to install latest mesa drivers and use Oracle jdk

**Comment by eduramiba** [comment]
Did it work?

**Comment by mbastian** [comment]
Thanks for reporting this. As filed, this issue doesn't have a reliable reproduction (a partial or unresolved stack trace, and no consistent steps to reproduce), and it's been open a long time without a way to confirm the cause. Since this was reported, Gephi 0.11 rebuilt the Overview rendering engine from scratch, so a lot has changed under the hood.

If you can still reproduce a crash or freeze on the latest 0.11.x release, please open a new, focused issue with your OS/GPU details, exact steps to reproduce, and a full log or stack trace. That will let us actually track it down. Closing this for now as not actionable as filed.
