### ISSUE TITLE
Location of GEXF 1.3 schema

### ISSUE THREAD

**Issue by FishOfPrey** [gephi/gephi#2019]
When importing a GEXF file I'm getting a message that the 1.2 XML schema is deprecated.

![image](https://user-images.githubusercontent.com/2396092/44635454-a54c6c00-a9f9-11e8-9149-56231c4d80b5.png)

I can't seem to find a location that defines the 1.3 schema.

I've tried https://gephi.org/gexf/format/schema.html and http://www.gexf.net/1.3/gexf.xsd, but I can't locate a working XSD for 1.3

## Context

I'd like to avoid the warnings when importing a gexf file defined with the available schema.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 1.8.1_121
* Operating System: Windows 10

**Comment by salotz** [comment]
I'm having the problem of gephi defaulting to the WIP gexf 1.3 by default. I would like to have the option for 1.2 so that my old tools (e.g. networkx) can still read them. Furthermore, it seems a little strange to use the WIP, undocumented format, where the schema links to a 404 be even an option at all without due warning...

**Comment by mbastian** [comment]
Closing this issue as it has been resolved via https://github.com/gephi/gexf/pull/13

All GEXF 1.3 specifications have been published and are accessible online.
