### ISSUE TITLE
csv export to use right locale. use comma instead of point in decimals

### ISSUE THREAD

**Issue by mihkal** [gephi/gephi#2072]
## Expected Behavior

when exporting csv file gephi does not respect locale for decimal numbers
here it is , instead of .

## Current Behavior

![image](https://user-images.githubusercontent.com/23520032/51428682-1130aa80-1c0f-11e9-9688-c0164f85df51.png)

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
* Operating System:

**Comment by eduramiba** [comment]
Hi,
As this CSV data is later to be parsed and auto-recognized as a number by Gephi in any computer in any locale, we use the kind-of-standard dot for decimal separator.

Anyway I think localizing CSV is a bad idea as it makes it not portable, which is not good since it is not normally written by humans with a text editor, but instead read and written by programs (like GEXF is).

**Comment by mihkal** [comment]
then add an option to export with right delimiter. it is really a lot work to make all decimals work in office applications like excel. this approch is NOT standard.

**Comment by eduramiba** [comment]
Right, we can add an option to override default settings.

**Comment by mihkal** [comment]
excellent :+1:

**Comment by mihkal** [comment]
Hello. Doing anything to this?

**Comment by eduramiba** [comment]
Adding to 0.9.3 milestone

**Comment by mbastian** [comment]
Thanks @mihkal! I added an option to CSV export to configure the decimal separator. In the long run, we could maybe have a global option to configure the Locale we use for all the numbers - also for import. For now, we prefer to stick with a single Locale (Locale.ENGLISH) instead of taking the system default locale as explicit is better in my opinion.
