### ISSUE TITLE
Import features to tables (eg. modularity class from outside Gephi) 

### ISSUE THREAD

**Issue by blas-ko** [gephi/gephi#2132]
## Expected Behavior
Being able to import features into the nodes/edges tables, such as your own modularity class.

## Current Behavior
One cannot import individual columns into existing tables. One has to export the table, work on them, and then import them again. 

## Possible Solution
This shouldn't be very hard to do with cross-referencing. If one has a notion of the ids/labels of eg. the nodes, one add columns into existing tables by matching those ids/labels

## Context
I made community detection for a graph using infomap, and I'll like to color my graphs in Gephi using those results instead of using the community detection algorithms in Gephi. 

## Your Environment

* Version used: Gephi 0.9.2
* Java version: 
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

* Operating System: Ubuntu 16.04

**Comment by eduramiba** [comment]
Hi,
This can already be done with the following steps:

1. Have an open workspace
2. Import the new CSV that has at least columns `id` and the new/changed attribute column.
3. During import report choose **merge into existing workspace**

Nodes/edges will be updated with the imported data based on `id`.

This can only work with `id` column since it's always unique in Gephi. It cannot work with `label` column because it's not always unique.
