### ISSUE TITLE
Dynamic Node Attributes Not Working When Play Timeline

### ISSUE THREAD

**Issue by jrnewm001** [gephi/gephi#2152]
### 

(correct behavior expected)
## Node Attribute (partitioned by COLOR) correctly Changing according to a DYNAMIC ATTRIBUTE COLUMN

(behavior experienced)
## Possible Solution

I do not know.

## Context: Trying to map a dynamic human network.
* Version used: Gephi 0.9.2
* Java version: 1.8 
* Operating System: Mac OS

**Comment by eduramiba** [comment]
Hi,
Are you using the apply continuously button (small) in appeareance? Otherwise it's only applied once and not in real-time for each dynamic change.

**Comment by jrnewm001** [comment]
No, I was not aware of this button. I cannot find it- may you please describe where it is located?

**Comment by jrnewm001** [comment]
I found it and figured it out. Thank you so much for your help!

**Comment by eduramiba** [comment]
Great!

**Comment by s-l-chausson** [comment]
This feature does not work for me. My data contains a dynamic attribute for nodes, which Gephi seems to parse correctly (see Data Laboratory tab). Moreover, the "Apply continuously" option is enabled (see Overview tab). However, even when I am further along in the timeline, the partition over my dynamic attribute only shows the distribution of this attribute's values at the very beginning of the timeline . In my case, at the very beginning of the timeline, all nodes have the value "active"... What am I doing wrong here? Is this a bug on Gephi's part? (I've redacted the network graph itself and some values from the Data Laboratory for privacy purposes)

<img width="1440" alt="Screenshot 2022-10-25 at 14 34 40" src="https://user-images.githubusercontent.com/91962528/197889185-a9959bdf-7ca0-443c-aa9f-a504acd4298d.png">
<img width="1440" alt="Screenshot 2022-10-25 at 14 34 50" src="https://user-images.githubusercontent.com/91962528/197889176-5969903b-0027-4f9c-9b31-e797d52ad2d6.png">

**Comment by mbastian** [comment]
Hi @s-l-chausson, I think what you're looking for is this option
<img width="1440" alt="197889176-5969903b-0027-4f9c-9b31-e797d52ad2d6" src="https://user-images.githubusercontent.com/234813/197988585-2ce02d5e-f8f7-4fab-8528-5433479fdea2.png">

With this option, the partitions will be based on the filtered graph. Essentially the slice you're currently selecting in the timeline.

**Comment by s-l-chausson** [comment]
Unfortunately this doesn't work either: the distribution of values stays exactly the same...

**Comment by mbastian** [comment]
Depending on the time range you select on the timeline you might also not see the partition values because of the Estimator you're using. By default the "FIRST" estimator is used. You may want to try "LAST" instead. 

The estimators need to be used when more than one value overlap with the selected time range.

Estimator can be configured as follow from the data laboratory:
<img width="904" alt="Screenshot 2022-10-26 at 21 47 52" src="https://user-images.githubusercontent.com/234813/198122602-557f84b5-7fa8-4e26-911e-0d0c0cf32f04.png">

If that still doesn't work, I'm not sure what might be wrong as this is the expected result. I would be happy to try on my own if you send me via email a sample file at mathieu.bastian [at] gephi.org

**Comment by s-l-chausson** [comment]
Alright, this seems to work! However, the dynamic filtering is very slow and the process eventually gets stuck. I'm guessing the problem might come from the network itself being really large (more than 129K nodes). I'll try to find a different solution. Thanks for your help in any case!
