### ISSUE TITLE
Next release (0.9.3)

### ISSUE THREAD

**Issue by EwoutH** [gephi/gephi#2351]
Currently gephi 0.9.2 is over four years old. I would love to use a stable version of gephi with all the accumulated [improvements](https://github.com/gephi/gephi/compare/v0.9.2...master). I noticed there is a [0.9.3 milestone](https://github.com/gephi/gephi/milestone/24), but no due date.

Of course a pre-release or release candidate before the stable release could also be useful.

**Comment by mbastian** [comment]
Hi there, 

We have [a developer retreat](https://gephi.wordpress.com/2021/08/23/call-for-participants-gephi-code-sustainability-retreat-2021/) planned at the end of this month. We hope to make good progress over there. If this is the case, I think we should be able to release a new version by the end of this year.

Nightly builds are normally available (see links on README) but at the moment builds are paused because we've exhausted our free credits on Travis-CI. Once this is resolved, one could download the 0.9.3 snapshots as we make progress. That said, the current version already includes some patches so feel free to use it instead of the 0.9.2.

Also, let me move this to discussion - thanks!
