### ISSUE TITLE
CVE-2021-44228 log4j

### ISSUE THREAD

**Issue by flagoda** [gephi/gephi#2386]
Hi, Gephi 0.9.2 looks like vulnerable to  CVE-2021-44228.
C:\Program Files\Gephi-0.9.2\gephi\modules\ext\org.gephi.desktop-branding\com-getsentry-raven\raven.jar contains com/getsentry/raven/config/JndiLookup.class
Is it plan an update ?

**Comment by wetneb** [comment]
Strictly speaking I would not say that Gephi is vulnerable to this CVE as it does not rely on log4j at all (as far as I can tell). If there is a similar vulnerability in the `raven` package, it should be reported and would likely get its own CVE number.
In any case, the next release will not contain this raven package since we have migrated to a newer version of the Sentry SDK earlier this month.

**Comment by wetneb** [comment]
Closing this for the reason above.
