### ISSUE TITLE
Can't connect to Twitter to import data

### ISSUE THREAD

**Issue by viniciuslimabr** [gephi/gephi#2464]
Hey guys, I'm trying to connect to Twitter with the plugin Twitter Import, but it ins't working. I put my access codes and follow all the steps, but nothing change. The data simple does not show up. I'm working in a Mac A1. I don't know if this would be the problem. Could you let me know if you see this before or know how can I fix that problem? Thank you.

**Comment by totetmatt** [comment]
Hello @viniciuslimabr ,
Did you try with a popular terms (like trending hashtag) to see if it reacts ? 
When you click on "Connect" is there a red icon on the bottom right that appears ? If so, would be helpful to have a copy paste of the 

Also did you create your twitter dev account and geenrate the the application credentials recently  ?

**Comment by viniciuslimabr** [comment]
Hello Matt, thank you for your help. I took a look in my permissions and I had to ask Twitter to elevated my access. Now it's working. Thanks.

**Comment by totetmatt** [comment]
Thanks @viniciuslimabr for the answer. 
Yeah unfortunately the change made by twitter on their api access start to change a little bit the "easy access" that the plugin could offer.
I'll try to review the tutorial as it's an issue that pop frequently theses days and also upgrade the plugin to maybe more compliant with new api.

**Comment by racarden** [comment]
Hi guys,
Have the same problem but I have the "Essential" permissions on my Twitter Account, however after putting my credentials and all the steps and click on "Connect" it does appear a red icon in the bottom right of the Gephi screen, with the error:

403:The request is understood, but it has been refused. An accompanying error message will explain why. This code is used when requests are being denied due to update limits (https://support.twitter.com/articles/15364-about-twitter-limits-update-api-dm-and-following).
<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\n<title>Error 403 
Please use V2 filtered and sample volume stream as alternatives
</title>
</head>
<body>
<h2>HTTP ERROR: 403</h2>
<p>Problem accessing '/1.1/statuses/filter.json'. Reason:
<pre>    
Please use V2 filtered and sample volume stream as alternatives
</pre>
</body>
</html>

Relevant discussions can be found on the Internet at:
	http://www.google.co.jp/search?q=1169356e or
	http://www.google.co.jp/search?q=df77bcd3
TwitterException{exceptionCode=[1169356e-df77bcd3], statusCode=403, message=null, code=-1, retryAfter=-1, rateLimitStatus=null, version=4.0.7}
	at twitter4j.HttpClientImpl.handleRequest(HttpClientImpl.java:170)
	at twitter4j.HttpClientBase.request(HttpClientBase.java:57)
	at twitter4j.HttpClientBase.post(HttpClientBase.java:86)
	at twitter4j.TwitterStreamImpl.getFilterStream(TwitterStreamImpl.java:356)
	at twitter4j.TwitterStreamImpl$8.getStream(TwitterStreamImpl.java:330)
	at twitter4j.TwitterStreamImpl$TwitterStreamConsumer.run(TwitterStreamImpl.java:570)
Caused: java.lang.UnsupportedOperationException
	at totetmatt.gephi.twitter.TwitterStreamer$1.accept(TwitterStreamer.java:205)
	at totetmatt.gephi.twitter.TwitterStreamer$1.accept(TwitterStreamer.java:201)
	at twitter4j.TwitterStreamImpl$10.onException(TwitterStreamImpl.java:447)
[catch] at twitter4j.TwitterStreamImpl$TwitterStreamConsumer.run(TwitterStreamImpl.java:612)

**Comment by totetmatt** [comment]
Known issue due to Twitter Api V1 deperaction on twitter side.
https://github.com/gephi/gephi/discussions/2530#discussioncomment-2738591

**Comment by AlienRebelll** [comment]
Hi guys, im trying to use the Streaming Importer V2 but I keep getting this error: A java.lang.NullPointerException exception has occured 

Can you help me fix it? Thanks!
