### ISSUE TITLE
Gephi 0.10.0 for macOS (Silicon) -- looks to be an intel version

### ISSUE THREAD

**Issue by stevemaser** [gephi/gephi#2726]
The link for the Silicon version:

https://github.com/gephi/gephi/releases/download/v0.10.0/gephi-0.10.0-macos-aarch64.dmg

Downloads an app that says it's an "Intel" version.    Did the wrong package get put in the Silicon .dmg?

<img width="266" alt="Screenshot 2023-01-09 at 9 13 39 AM" src="https://user-images.githubusercontent.com/73914398/211328188-59e1b9d9-8d63-4613-83d4-cb5dc871603f.png">

**Comment by mbastian** [comment]
Hi @stevemaser this may be the case because of the launcher app we use. But that launcher starts another process that is on aarch64. You can see that in the About window it shows `aarch64`:

<img width="331" alt="Screenshot 2023-01-09 at 15 32 44" src="https://user-images.githubusercontent.com/234813/211390650-49bf6432-8e58-4188-a877-fffdda9adcc9.png">

**Comment by stevemaser** [comment]
Ah, OK.  We usually check the app's "Get Info" screen here.  I see what you describe here.
