### ISSUE TITLE
Partition colors generated at each workspace switch

### ISSUE THREAD

**Issue by sheymann** [gephi/gephi#453]
Hi,

I'm using different workspace and have set not colors according to partitions. When I go to another workspace and come back, the colors in the panel have changed, making useless to edit the colors to use them consistently across the workspaces.

**Comment by mbastian** [comment]
This has been fixed in trunk but let me clarify because the description isn't very clear. What we want is partition/ranking settings to "stick" to each workspace. Meaning if I configure colors X in workspace A and then I configure colors Y in workspace B and then I go back to workspace A I want to see colors X. 

Then, it's sometimes useful to use the same colors ACROSS workspaces (when comparing graphs for instance). For that purpose we don't have a mechanism built-in but the "Recent" menu in both partition and ranking should make that easy enough.
