### ISSUE TITLE
Add a local/global scale button to Ranking

### ISSUE THREAD

**Issue by mbastian** [gephi/gephi#541]
Then ranking function currently uses only the visible graph for calculating the bounds. That makes comparaison between views difficult because the scale is modified. To address this use case we should have the ability to use ranking on a global scale. A global scale means that the min/max would be computed on the main view rather than on the visible view.

This issue is discussed in this topic:
http://forum.gephi.org/viewtopic.php?f=30&t=1501

**Comment by MatthiasSL** [comment]
Sorry to post on an old ticket, but where is the local/global ranking button located in 0.9.2? I'm trying to follow [this tutorial](https://edisciplinas.usp.br/pluginfile.php/2671054/mod_resource/content/1/gephi_tutorial_dynamics.pdf#page=19) (slide 19), but the button seems to have been (re)moved since then? I seem to recall similar buttons and sliders being relegated to the statistics tab, but I can't find anything there that would correspond to this.

Thanks in advance.
