### ISSUE TITLE
Import graph on current workspace if empty

### ISSUE THREAD

**Issue by sheymann** [gephi/gephi#548]
Currently importing a new graph creates a new workspace. This is cluttering a bit the UI in most cases when the user open Gephi and load a graph directly.

We should check at import if the current workspace is empty, and in this case fill it with the new graph.

**Comment by mbastian** [comment]
I suggest to close this issue unless someone has a good idea how to solve this:
- Generally, I don't think this is a big issue as users can open a graph file directly, without having to create a project first. Not sure if that was the case when this issue was created. If they do that, they only get one workspace.
- I though about pre-selecting "Append to New workspace" on the Report Panel in case the current workspace i empty. But unfortunately as processors are dynamic the report panel doesn't know anything about that.
