### ISSUE TITLE
missing nodes and edges in DOT file

### ISSUE THREAD

**Issue by UniIsland** [gephi/gephi#669]
I noticed some nodes and edges are missing when i open this dot file with gephi.
https://gist.github.com/3565653

missing nodes:

```
"根" - this is actually the root node of this directed graph
```

missing edges:

```
{清朝; 皇帝} -> 清朝皇帝
{IPO; 美股投资} -> "Facebook IPO"
金融产业 -> IPO
Facebook -> "Facebook IPO"
```

and there should be other missing nodes and edges.

is there anything wrong with my file syntax?
or does gephi encounter any error parsing this file?

**Comment by wetneb** [comment]
I just tried importing this file in the latest development version and I can find both the node and the edges you mentioned. So I suspect this has been fixed already, which is likely since this issue is very old. Therefore closing, but we can of course reopen if the problem still appears on your side.
