### ISSUE TITLE
Force Atlas hangs during dynamic

### ISSUE THREAD

**Issue by lynchs61** [gephi/gephi#736]
When I play a dynamic graph while the force atlas (or force atlas 2) is
running it hangs about 75% of the time. When this happens the graph
continues to change according to the dynamic timeline, but the vertices
no longer respond to the layout algorithm. Also the layout algorithm
shows that it is running and can't be stopped (hitting the stop
button does nothing). The only way to restore normal behavior is to quit
the entire application.

This happens for me with every dynamic graph I've tried in gexf format,
and also if I use "File > Generate > Dynamic Graph Example..." from the
menu. It happens with version 0.8.1-beta, 0.8.2-beta, and 0.9-snapshot,
on Ubuntu Linux, and with 0.8.2-beta on OS X.

**Comment by mbastian** [comment]
This should have been fixed with Gephi 0.9.0. Please try again and reopen if it still doesn't work.

**Comment by richardheuver** [comment]
Will do!
________________________________
Van: Mathieu Bastian<mailto:notifications@github.com>
Verzonden: ‎9-‎2-‎2016 11:39
Aan: gephi/gephi<mailto:gephi@noreply.github.com>
CC: Richard Heuver<mailto:richardheuver@hotmail.nl>
Onderwerp: Re: [gephi] Force Atlas hangs during dynamic (#736)

This should have been fixed with Gephi 0.9.0. Please try again and reopen if it still doesn't work.

---
