### ISSUE TITLE
cant open Gephi 0.8.2 after installation

### ISSUE THREAD

**Issue by MichelleHeart** [gephi/gephi#886]
I cant open Gephi 0.8.2 after installation. No error message. Once I launch the application it will  open but after a few seconds it will close automatically. Any resolution please??

**Comment by eduramiba** [comment]
Possible duplicate of #748

Gephi does not work in Mac OS since Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.
