### ISSUE TITLE
Gephi won't start I have Java

### ISSUE THREAD

**Issue by ar25801** [gephi/gephi#903]
I have Mac OS 10.9.2 and Java 7 with Update 51.
I installed Gephi (both 0.8.2 and an earlier verssion) and it simply won0t start. I double click, the icon expands, and nothing happens. What can I do?

**Comment by clinttuttle** [comment]
ironfrown or anyone else - Any hints on how I'd fix this on a Mac running OSX10.10.2?

**Comment by rwreed** [comment]
Some more information about this issue:

The problem occurs in NetBeans code, and is due to a change made in Java 8.  NetBeans fixed this in February 2014.  Here's a link to the bug in their system: 

https://netbeans.org/bugzilla/show_bug.cgi?id=229191

This should have been fixed by commit 2e8ddc for Gephi, which has been merged into the 0.8.2 stable branch, but I don't believe the available downloads have been rebuilt to include it.  The date I have on gephi.exe is 1/04/2013, and the commit was made on 7/31/2014.

**Comment by SigmaX** [comment]
It appears that active development of Gephi ceased in August of 2014.

Since Oracle has ended support for Java 7, anybody working for a company with a rigorous security policy will not be permitted to install Java 7.  So until somebody gets around to updating the install packages, Gephi will lose a lot of its potential user base.

**Comment by rumtscho** [comment]
@SigmaX it's not ceased, they are busy doing a very large rewrite and cannot release the half-refactored version. See https://gephi.wordpress.com/2015/02/25/gephi-is-asleep-and-up-to-awaken/ for details.

**Comment by SigmaX** [comment]
Excellent, good to know!

**Comment by narfman0** [comment]
For the googlers, try using the nightly snapshot (worked for me): https://github.com/gephi/gephi#nightly-builds

**Comment by buzzworkers** [comment]
on archilinux it's quite easy to fix this issue : 

get openjdk 7 installed along version 8 (or if you need it for other software use)

type in your terminal : archlinux-java
to check the available commands of this tool

archlinux-java status to see what version of java is being used

archlinux-java set (to set the openjdk version to be used by default)

then go to $SOMELOC/gephi/etc/gephi.conf and insert the default java path
and uncomment (#) the line

set the java version you want to use with archlinux-java

from there, Gephi should be working fine.

**Comment by Foxboron** [comment]
In regard to arch, i recreated the AUR package and added a sed line to append the correct jdk path.
https://aur.archlinux.org/packages/gephi/

It working now \o/

**Comment by eduramiba** [comment]
Duplicate of #748

Gephi does not work in Mac OS sine Java 7 and Windows since Java 8.
It's due to problems with old JOGL version and is going to be updated in next version.

Please check https://forum.gephi.org/viewtopic.php?f=3&t=3580&p=10712#p10712 for help about running Gephi with Java 6.

**Comment by proopnarine** [comment]
I recently upgraded to Opensuse 13.2 from Fedora 20 and ran into this problem. ironfrown's fix works, but with a slight modification. I could not get it to work with openjdk 1.7.0, so installed openjdk 1.6 (rpm available at https://software.opensuse.org/package/java-1_6_0-openjdk), and modified the gephi/etc/gephi.conf file by adding the line
jdkhome="/usr/lib64/jvm/jre-1.6.0-openjdk"
Finally works. The Gephi developers really should fix this to upgrade to the latest Java versions because of security issues, but, I do understand that it's a lot of work involved.

**Comment by ironfrown** [comment]
Good news! The new Gephi 0.9 works with Java 8! (at least in Windows 8.1 Pro).

**Comment by acriptis** [comment]
@ironfrown thanks! That works

**Comment by ironfrown** [comment]
@acriptis I am glad that my workaround still works after so many years of Gephi not working :)
